### ISSUE TITLE
Error: Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by alm22324** [j796160836/homebridge-sengled#3]
The error:
Error: Accessories must be created with a non-empty displayName.

at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:15:27)

at Server._loadCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:235:31)

at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:58:42)

at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)

at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

at Module._compile (module.js:660:30)

at Object.Module._extensions..js (module.js:671:10)

at Module.load (module.js:573:32)

at tryModuleLoad (module.js:513:12)

at Function.Module._load (module.js:505:3)

at Function.Module.runMain (module.js:701:10)

at startup (bootstrap_node.js:190:16)

at bootstrap_node.js:662:3

**Comment by j796160836** [comment]
Hi @alm22324,
Have you name your light bulb a name in sengled element?
Can you update it? I just push a version to npm, thanks.

**Comment by alm22324** [comment]
Perfect! It works now.

**Comment by j796160836** [comment]
Great! I close the issue. Kindly open another if you encounter issues.
