### ISSUE TITLE
Throwing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by godrifle** [j796160836/homebridge-sengled#7]
[SengledHub] DeviceDiscovery invoked
(node:1137) UnhandledPromiseRejectionWarning: Error: timeout of 2000ms exceeded
    at createError (/usr/lib/node_modules/homebridge-sengled/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/usr/lib/node_modules/homebridge-sengled/node_modules/axios/lib/adapters/http.js:207:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

Perhaps this is my fault for not configuring it correctly. What is the source of the username and password values for the Sengled hub which are asked for in config.json?

**Comment by j796160836** [comment]
Umm...It looks like timeout. 😓

**Comment by j796160836** [comment]
> What is the source of the username and password values for the Sengled hub which are asked for in config.json?

Here is the steps for register a Sengled account.

Download original Sengled comparison app.
Sengled Element Home

[iOS] App Store
https://apps.apple.com/tw/app/sengled-element-home/id1147997004

[Android] Google Play
https://play.google.com/store/apps/details?id=com.sengled.zigbee.eu&hl=en_US

and then follow the account register step.
then bind your leds.

**Comment by whysheep** [comment]
FYI, I see the same thing. I do have the Sengled configuration in the homebridge config.json and it even works...but I still see this complaint every 5 minutes in the log.

**Comment by brewerc1** [comment]
This error goes away with an edit of line 38 to increase timeout from 2000 to 3000 in /usr/local/lib/node_modules/homebridge-sengled/lib/client.js.

The timeout appears in the constructor for this.client = axios.create({

**Comment by hinsno** [comment]
Do you know if there is a command in the terminal I can input to change the timeout?

**Comment by sequencentropy** [comment]
> Do you know if there is a command in the terminal I can input to change the timeout?

I am curious also - I'm not a CLI overlord, so if someone could spell the fix out it'd be much appreciated.

**Comment by brewerc1** [comment]
> > Do you know if there is a command in the terminal I can input to change the timeout?
> 
> I am curious also - I'm not a CLI overlord, so if someone could spell the fix out it'd be much appreciated.

Use a text editor (such as vi or vim in command line) or something like Visual Studio Code if you're a GUI person to edit the file I mention in my Sept. 21, 2020 comment.
